sudo: required
services:
  - docker

before_install:
  - docker build -t/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anuroopps/react-test npm test 

after_success:
  - docker build -t anuroopps/multi-client -f ./client/Dockerfile.prod./client
  - docker build -t anuroopps/multi-nginx -f ./nginx/Dockerfile.prod ./nginx
  - docker build -t anuroopps/multi-server -f ./server/Dockerfile.prod./server
  - docker build -t anuroopps/multi-worker -f ./worker/Dockerfile.prod ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push anuroopps/multi-client
  - docker push anuroopps/multi-nginx
  - docker push anuroopps/multi-server
  - docker push anuroopps/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
